import type { IsdId, IsdState, IsdStateUpdate } from "@/types"

export const INITITAL_ISD_STATE: IsdState = {
  cover_state: 0,
  adc_fov: 0,
  svc_enabled: 0,
  vph_gr_grism: 1,
  vph_zi_grism: 1,
  vph_jy_grism: 1,
  vph_hk_grism: 1,
  shutter_g: 0,
  shutter_r: 0,
  shutter_z: 0,
  shutter_i: 0,
  adc_control: 0,
  adc_pos_diff: 0,
  adc_pos_joint: 0,
  detg_temp: 0,
  detr_temp: 0,
  deti_temp: 0,
  detz_temp: 0,
  detj_temp: 0,
  dety_temp: 0,
  deth_temp: 0,
  detk_temp: 0,
  bench_1: 0,
  bench_2: 0,
  bench_3: 0,
  bench_4: 0,
  bench_a1: 0,
  bench_a2: 0,
  bench_a3: 0,
  bench_a4: 0,
  bench_b1: 0,
  bench_b2: 0,
  bench_b3: 0,
  bench_b4: 0,
  vph_gr_health: 0,
  vph_hk_health: 0,
  vph_jy_health: 0,
  vph_zi_health: 0,
  deth_health: 0,
  detk_health: 0,
  detj_health: 0,
  dety_health: 0,
  detgr_health: 0,
  detzi_health: 0,
  svc_health: 0,
  pic_health: 0,
  num_shift_rows: 0,
  num_abba_seq: 0,
  obs_time_left: 1,
  obs_time_total: 1,
  obs_mode: 0,
  obs_strategy: 0,
  scorpio_health: 0,
  adc_health: 0,
  cryo_health: 0,
  fp_health: 0,
  obs_data_label: 0,
  obs_state: 0,
  obs_type: 0,
}

export function isdState(state: Record<IsdId, number>, data: IsdStateUpdate[]) {
  if (data.length > 0) {
    const newStates = data.reduce(
      (acc, update) => {
        acc[update.id] = update.value
        return acc
      },
      {} as Record<IsdId, number>,
    )

    return {
      ...state,
      ...newStates,
    }
  } else {
    return state
  }
}

export const STATE_OPTIONS = [
  {
    name: "cover_state",
    ref: "SCO:CC:cover.cover",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "adc_pos_diff",
    ref: "SCO:CC:ADC.diffPrism",
    type: "double",
    options: [0, 1],
  },
  {
    name: "adc_pos_joint",
    ref: "SCO:CC:ADC.jointPrism",
    type: "double",
    options: [0, 1],
  },
  {
    name: "adc_control",
    ref: "SCO:CC:ADC.prismControl",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "adc_fov",
    ref: "SCO:CC:ADC.corrector",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "svc_enabled",
    ref: "SCO:DC:SVC.enabled",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "vph_gr_grism",
    ref: "SCO:CC:VPH_gr.grism",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "vph_zi_grism",
    ref: "SCO:CC:VPH_zi.grism",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "vph_jy_grism",
    ref: "SCO:CC:VPH_jy.grism",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "vph_hk_grism",
    ref: "SCO:CC:VPH_hk.grism",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "shutter_g",
    ref: "SCO:DC:VIS_gr.shutterG",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "shutter_r",
    ref: "SCO:DC:VIS_gr.shutterR",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "shutter_z",
    ref: "SCO:DC:VIS_zi.shutterZ",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "shutter_i",
    ref: "SCO:DC:VIS_zi.shutterI",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "obs_time_left",
    ref: "SCO:IS:obs.timeLeft",
    type: "integer",
    options: [0, 5, 10, 15, 20],
  },
  {
    name: "obs_time_total",
    ref: "SCO:IS:obs.timeTotal",
    type: "integer",
    options: [0, 5, 10, 15, 20],
  },
  {
    name: "detg_temp",
    ref: "SCO:CC:DET:temp_gr.detector_g",
    type: "double",
    options: [0, 1],
  },
  {
    name: "detr_temp",
    ref: "SCO:CC:DET:temp_gr.detector_r",
    type: "double",
    options: [0, 1],
  },
  {
    name: "deti_temp",
    ref: "SCO:CC:DET:temp_iz.getector_i",
    type: "double",
    options: [0, 1],
  },
  {
    name: "detz_temp",
    ref: "SCO:CC:DET:temp_iz.detector_z",
    type: "double",
    options: [0, 1],
  },
  {
    name: "detj_temp",
    ref: "SCO:CC:DET:temp_J.detector",
    type: "double",
    options: [0, 1],
  },
  {
    name: "dety_temp",
    ref: "SCO:CC:DET:temp_Y.detector",
    type: "double",
    options: [0, 1],
  },
  {
    name: "deth_temp",
    ref: "SCO:CC:DET:temp_H.detector",
    type: "double",
    options: [0, 1],
  },
  {
    name: "detk_temp",
    ref: "SCO:CC:DET:temp_K.detector",
    type: "double",
    options: [0, 1],
  },
  {
    name: "bench_1",
    ref: "SCO:CC:DET:temp_vis.bench1",
    type: "double",
    options: [0, 1],
  },
  {
    name: "bench_2",
    ref: "SCO:CC:DET:temp_vis.bench2",
    type: "double",
    options: [0, 1],
  },
  {
    name: "bench_3",
    ref: "SCO:CC:DET:temp_vis.bench3",
    type: "double",
    options: [0, 1],
  },
  {
    name: "bench_4",
    ref: "SCO:CC:DET:temp_vis.bench4",
    type: "double",
    options: [0, 1],
  },
  {
    name: "num_shift_rows",
    ref: "SCO:IS.obs.num_shift_rows",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "num_abba_seq",
    ref: "SCO:IS.obs.num_abba_seq",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "bench_a1",
    ref: "SCO:CC:DET:temp_nir.benchA1",
    type: "double",
    options: [0, 1],
  },
  {
    name: "bench_a2",
    ref: "SCO:CC:DET:temp_nir.benchA2",
    type: "double",
    options: [0, 1],
  },
  {
    name: "bench_a3",
    ref: "SCO:CC:DET:temp_nir.benchA3",
    type: "double",
    options: [0, 1],
  },
  {
    name: "bench_a4",
    ref: "SCO:CC:DET:temp_nir.benchA4",
    type: "double",
    options: [0, 1],
  },
  {
    name: "bench_b1",
    ref: "SCO:CC:DET:temp_nir.benchB1",
    type: "double",
    options: [0, 1],
  },
  {
    name: "bench_b2",
    ref: "SCO:CC:DET:temp_nir.benchB2",
    type: "double",
    options: [0, 1],
  },
  {
    name: "bench_b3",
    ref: "SCO:CC:DET:temp_nir.benchB3",
    type: "double",
    options: [0, 1],
  },
  {
    name: "bench_b4",
    ref: "SCO:CC:DET:temp_nir.benchB4",
    type: "double",
    options: [0, 1],
  },
  {
    name: "obs_mode",
    ref: "SCO:IS.obs.obs_mode",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "obs_strategy",
    ref: "SCO:IS.obs.obs_strategy",
    type: "integer",
    options: [0, 1],
  },
  { name: "scorpio_health", ref: "", type: "integer", options: [0, 1] },
  {
    name: "adc_health",
    ref: "SCO:CC:ADC_CC.adc_health",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "cryo_health",
    ref: "SCO:DET:CRYO.cryo_health",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "vph_gr_health",
    ref: "SCO:CC:VPH_gr.health",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "vph_hk_health",
    ref: "SCO:CC:VPH_hk.health",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "vph_jy_health",
    ref: "SCO:CC:VPH_jy.health",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "vph_zi_health",
    ref: "SCO:CC:VPH_zi.health",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "fp_health",
    ref: "SCO:CC:FP.health",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "deth_health",
    ref: "SCO:DC:NIR_h.health",
    type: "integer",
    options: [0, 1, 2, 3],
  },
  {
    name: "detk_health",
    ref: "SCO:DC:NIR_k.health",
    type: "integer",
    options: [0, 1, 2, 3],
  },
  {
    name: "detj_health",
    ref: "SCO:DC:NIR_j.health",
    type: "integer",
    options: [0, 1, 2, 3],
  },
  {
    name: "dety_health",
    ref: "SCO:DC:NIR_y.health",
    type: "integer",
    options: [0, 1, 2, 3],
  },
  {
    name: "pic_health",
    ref: "SCO:DC:PIC.health",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "svc_health",
    ref: "SCO:DC:SVC.health",
    type: "integer",
    options: [0, 1],
  },
  {
    name: "detgr_health",
    ref: "SCO:DC:VIS_gr.health",
    type: "integer",
    options: [0, 1, 2, 3],
  },
  {
    name: "detzi_health",
    ref: "SCO:DC:VIS_zi.health",
    type: "integer",
    options: [0, 1, 2, 3],
  },
  { name: "obs_data_label", ref: "", type: "integer", options: [0, 1] },
  { name: "obs_state", ref: "", type: "integer", options: [0, 1] },
  { name: "obs_type", ref: "", type: "integer", options: [0, 1] },
]

export const SCRIPT_OPTIONS = [
  { name: "Rotate ADC", id: "adcRotate" },
  { name: "Observation Example", id: "observationExample" },
  { name: "yet_another_script", id: "yetAnotherScript" },
]
